---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
    - os: linux
      dist: xenial
      sudo: true
    - os: linux
      dist: precise
      sudo: true

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Full install check
  - sudo ansible-playbook tests/test.yml -i tests/inventory
  - sudo netstat -nlp |grep 9000
  # Http port checking
  - curl 'http://localhost:8123'
  - echo 'SELECT 1' | curl 'http://testuser2:testplpassword@localhost:8123?database=testu2' -d @-
  # Clickhouse client checking
  - clickhouse-client -q 'select 1'
  - clickhouse-client -q 'select 1' -d default
  - clickhouse-client -q 'select 1' -d testu1
  - clickhouse-client -q 'select 1' -d testu2 -u testuser2 --password testplpassword
  - clickhouse-client -q 'select 1' -d testu3


#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/