- name: Config | Generate system config
  template:
   src: config.j2
   dest: "{{ clickhouse_path_configdir }}/config.xml"
  notify: restart-ch
  become: true

- name: Config | Generate users config
  template:
   src: users.j2
   dest: "{{ clickhouse_path_configdir }}/users.xml"
  notify: restart-ch
  become: true

- meta: flush_handlers



