- name: Check clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    owner: clickhouse
    group: clickhouse
    state: directory
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  notify: restart-ch
  become: true

- name: Config | Generate system config
  template:
   src: config.j2
   dest: "{{ clickhouse_path_configdir }}/config.xml"
   owner: clickhouse
   group: clickhouse
  notify: restart-ch
  become: true

- name: Config | Generate users config
  template:
   src: users.j2
   dest: "{{ clickhouse_path_configdir }}/users.xml"
   owner: clickhouse
   group: clickhouse
  notify: restart-ch
  become: true

- name: Config | Create conf.d directory
  file:
   path: "{{ clickhouse_path_configdir }}/conf.d"
   owner: clickhouse
   group: clickhouse
   mode: 0755

- name: Config | Generate remote_servers config
  template:
   src: remote_servers.j2
   dest: "{{ clickhouse_path_configdir }}/conf.d/remote_servers.xml"
   owner: clickhouse
   group: clickhouse
  notify: restart-ch
  become: true
  when: clickhouse_shards is defined 

- meta: flush_handlers



