- name: Config | Generate users config
  template:
   src: users.j2
   dest: "{{ clickhouse_path_configdir }}/users.xml"
  notify: restart-ch
  become: true

- name: Config | Create database config
  command: "clickhouse-client -q 'CREATE DATABASE IF NOT EXISTS {{ item }}'"
  with_items: "clickhouse_dbs"

