#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Install by APT | Apt-key add yandex repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E0C56BD4

- name: Install by APT | Repo installation
  apt_repository:
    repo: "{{ clickhouse_repo }}"
    state: present

- name: Install by APT | Package installation
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ clickhouse_package }}"