---
# tasks file for clickhouse
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- include: precheck.yml
  tags: [precheck]

- name: Debug installed
  debug: var=clickhouse_rt_isinstalled.rc

- include: install_apt.yml
  when: ansible_pkg_mgr == 'apt' and clickhouse_setup == 'package' and clickhouse_rt_isinstalled.rc !=0 and clickhouse_remove|bool == False
  tags: [install]

- include: remove_apt.yml
  when: ansible_pkg_mgr == 'apt' and clickhouse_setup == 'package' and clickhouse_rt_isinstalled.rc == 0 and clickhouse_remove|bool == True
  tags: [install]

- include: config.yml
  when: clickhouse_rt_isinstalled.rc == 0 and clickhouse_remove|bool == False
  tags: [config]
