#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Uninstall by APT | Package uninstallation
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ clickhouse_package }}"

- name: Uninstall by APT | Repo uninstallation
  apt_repository:
    repo: "{{ clickhouse_repo }}"
    state: absent

- name: Uninstall by APT | Apt-key remove yandex repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E0C56BD4
    state: absent
